name: Scheduled Workflow

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Also allow manual trigger

jobs:
  scheduled-job:
    name: Daily Health Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run health check
      run: |
        echo "Running daily health check at $(date)"
        pytest test_app.py -v
        python app.py
        
    - name: Report status
      run: |
        echo "Health check completed successfully!"
        echo "Repository: ${{ github.repository }}"
        echo "Workflow: ${{ github.workflow }}"
        echo "Run number: ${{ github.run_number }}"
