name: Verify Login Scripts

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  verify-login:
    runs-on: windows-latest

    steps:
      - name: Create temp folder
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "C:\temp"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Python login test
        shell: pwsh
        run: |
          python login_test/show_login.py
          Add-Content -Path "C:\temp\verify_login_result.txt" -Value "Python script finished: $(Get-Date)"

      - name: Run Batch login test
        shell: cmd
        run: |
          login_test\show_login.bat
          echo Batch script finished: %DATE% %TIME% >> C:\temp\verify_login_result.txt

      - name: Run PowerShell login test
        shell: pwsh
        run: |
          pwsh login_test/show_login.ps1
          Add-Content -Path "C:\temp\verify_login_result.txt" -Value "PowerShell script finished: $(Get-Date)"

      - name: Show log file contents
        shell: pwsh
        run: |
          Get-Content "C:\temp\verify_login_result.txt"

      - name: All scripts completed
        run: echo "✅ All login scripts ran successfully!"
