name: Verify Login (BAT→PS + Py)

on:
  workflow_dispatch:
  push:
    branches: ['**']

jobs:
  verify-login:
    runs-on: [self-hosted, leaoserver]

    steps:
      - name: Ensure log folder
        shell: cmd
        run: if not exist C:\temp\action_log\ mkdir C:\temp\action_log\

      - name: Checkout
        uses: actions/checkout@v4

      - name: Reset log
        shell: cmd
        run:  echo [RUN] %DATE% %TIME% - fresh run > C:\temp\action_log\verify_login_script.txt

      - name: Run login (BAT→PowerShell)
        shell: cmd
        timeout-minutes: 5
        env:
          TARGET_HOST: leaoserver
          TARGET_SHARE: c
          AUTH_DOMAIN: ""
          GHA_USERNAME: ${{ secrets.USERNAME }}
          GHA_PASSWORD: ${{ secrets.PASSWORD }}
        run: login_test\show_login.bat

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Python login test
        shell: powershell
        env:
          TARGET_HOST: leaoserver
          TARGET_SHARE: c
          AUTH_DOMAIN: ""
          GHA_USERNAME: ${{ secrets.USERNAME }}
          GHA_PASSWORD: ${{ secrets.PASSWORD }}
        run: python login_test\show_login.py

      - name: Show log
        shell: powershell
        run: Get-Content C:\temp\action_log\verify_login_script.txt

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: verify_login_log
          path: C:\temp\action_log\verify_login_script.txt
