name: Verify Login Scripts

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  verify-login:
    runs-on: [self-hosted, leaoserver] # Ensure this matches your runner label

    steps:
      - name: Create temp folder
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "C:\temp"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log computer name and timestamp
        shell: pwsh
        run: |
          Add-Content -Path "C:\temp\verify_login_result.txt" -Value "Workflow run on $env:COMPUTERNAME at $(Get-Date)"

      - name: Run Python login test
        shell: pwsh
        run: |
          python login_test/show_login.py

      - name: Run Batch login test
        shell: cmd
        run: |
          login_test\show_login.bat

      - name: Run PowerShell login test
        shell: pwsh
        run: |
          pwsh login_test/show_login.ps1

      - name: Show log file contents
        shell: pwsh
        run: |
          Get-Content "C:\temp\verify_login_result.txt"
