name: Verify Login Scripts (Batch only)

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  verify-login:
    runs-on: [self-hosted, leaoserver]

    env:
      TARGET_HOST: leaoserver
      TARGET_SHARE: c              # <- your working share
      AUTH_DOMAIN: ""              # e.g., CORP if needed; else ""
      GHA_USERNAME: ${{ secrets.USERNAME }}
      GHA_PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Make log folder (cmd)
        shell: cmd
        run: |
          if not exist C:\temp\action_log\ mkdir C:\temp\action_log\

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Reset log file (cmd)
        shell: cmd
        run: |
          > C:\temp\action_log\verify_login_script.txt echo [RUN] %DATE% %TIME% - fresh run

      - name: Run Batch login test (pure BAT)
        shell: cmd
        run: login_test\show_login.bat

      - name: Show log file (cmd)
        shell: cmd
        run: type C:\temp\action_log\verify_login_script.txt
