name: Verify Login Scripts

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  verify-login:
    runs-on: [self-hosted, leaoserver]

    # Passed to all steps (scripts read these)
    env:
      TARGET_HOST: leaoserver            # change to FQDN or IP if needed
      TARGET_SHARE: c              # change to an existing share, e.g. Public
      AUTH_DOMAIN: ""                  # e.g. CORP ; leave empty if not needed
      GHA_USERNAME: ${{ secrets.USERNAME }}
      GHA_PASSWORD: ${{ secrets.PASSWORD }}
      
    steps:
      - name: Create temp folder
        shell: PowerShell
        run: New-Item -ItemType Directory -Force -Path "C:\temp\action_log\" | Out-Null

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Batch login test
        shell: cmd
        run: login_test\show_login.bat

      - name: Run PowerShell login test
        shell: PowerShell
        run: pwsh -File login_test/show_login.ps1

      - name: Ensure Python is available (optional)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Python login test
        shell: PowerShell
        run: python login_test/show_login.py

      - name: Show log file contents
        shell: PowerShell
        run: Get-Content "C:\temp\action_log\verify_login_script.txt"
